# Generated by Django 5.2.12 on 2026-03-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("brand", models.CharField(max_length=100)),
                ("commercial_name", models.CharField(max_length=200)),
                ("colour", models.TextField(blank=True, default="")),
                ("usp_1", models.TextField(blank=True, default="")),
                ("usp_2", models.TextField(blank=True, default="")),
                ("usp_3", models.TextField(blank=True, default="")),
                ("usp_4", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products",
                "ordering": ["product_id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_number", models.PositiveIntegerField()),
                ("ram", models.CharField(blank=True, default="", max_length=20)),
                ("rom", models.CharField(blank=True, default="", max_length=20)),
                ("unit_price", models.BigIntegerField(blank=True, null=True)),
                ("installment", models.BigIntegerField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_variants",
                "ordering": ["variant_number"],
                "unique_together": {("product", "variant_number")},
            },
        ),
    ]
