# Generated by Django 5.2.12 on 2026-03-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("demo", "Demo Item"), ("accessory", "Accessories Item")],
                default="demo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
