# Generated by Django 5.2.12 on 2026-03-25 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planogram", "0001_initial"),
        ("products", "0002_product_product_type_alter_product_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ESLDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("barcode", models.CharField(max_length=200)),
                ("template", models.CharField(blank=True, default="", max_length=50)),
                ("ap", models.CharField(blank=True, default="", max_length=100)),
                ("desc", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="esl_devices",
                        to="products.product",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="planogram.layoutsegment",
                    ),
                ),
            ],
            options={
                "db_table": "esl_devices",
                "ordering": ["barcode"],
            },
        ),
    ]
