# Generated by Django 5.2.12 on 2026-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planogram", "0002_esldevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="ESLTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_id", models.IntegerField(unique=True)),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "esl_templates",
                "ordering": ["template_id"],
            },
        ),
    ]
