# Generated by Django 5.2.12 on 2026-03-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planogram", "0003_esltemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="esltemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("demo", "Demo Item"),
                    ("accessory", "Accessories"),
                    ("maintenance", "UnderMaintenance"),
                ],
                default="demo",
                max_length=20,
            ),
        ),
    ]
