# Generated by Django 5.2.12 on 2026-03-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planogram", "0004_esltemplate_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="esltemplate",
            name="variant_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
